### ISSUE TITLE
Using Cypress will cause Hydration Problems.

### ISSUE THREAD

**Issue by gripzyyy** [expatfile/next-runtime-env#107]
Hello!
I have been trying to implement Cypress E2E testing in my application that relies on next-runtime-dev. I am using the Next.j 14 with the App Router.
I don't normally get any issues, but whenever I load up my website in the Cypress controlled browser (I tried Chrome and Edge) I will get this error: https://gist.github.com/gripzyyy/3f0e314c5de2aafa5be7342300106eba
Because of this I can not run any cypress tests. Deleting the <head> element from my layout that has the PublicEnvScript will remove that error. I have tried using supressHydrationWarning but it won't work. There is no support from Next.js regarding how to fully ignore this error also.

**Comment by HofmannZ** [comment]
Can you provide some more details on how you've implemented the `PublicEnvScript`? We use Cypress as well but don't have this issue. We'd happily point you in the right direction.

**Comment by gripzyyy** [comment]
@HofmannZ 
I just put this in the RootLayout
<html lang="en">
      <head>
        <PublicEnvScript />
      </head>

      <body
        id="__next"
      >
        other stuff...
      </body>
    </html>

**Comment by HofmannZ** [comment]
@gripzyyy - Do you have CSP enabled?

**Comment by HofmannZ** [comment]
We have rolled out patch `3.2.2-alpha.3` that should resolve the issue.
