### ISSUE TITLE
It does not read values when I reload a page of a subroute

### ISSUE THREAD

**Issue by gabrielcon6** [expatfile/next-runtime-env#124]
Whenever I have a subroute, for example user/details and I manually reload the page, the app breaks because it cannot find .env values. 

I am using PublicEnvScript as suggested and I have all my vars with the NEXT_PUBLIC_ prefix:

import { PublicEnvScript } from 'next-runtime-env';
...
  return (
    <html lang="en">
      <head>
        <PublicEnvScript />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
  
  Anyone able to help pls?
  
  Versions:
        "next": "^14.2.2",
        "next-runtime-env": "^3.2.1",
        "react": "^18.2.0",

**Comment by rzzapp** [comment]
@gabrielcon6 you closed this issue, how did yo fix it? I'm in same boat as you currently.
