### ISSUE TITLE
Should next-runtime-env work with Docker and docker-compose?

### ISSUE THREAD

**Issue by YerayAlonso** [expatfile/next-runtime-env#40]
I've tested the package and it works wonderfully in the examples you provide 🎉.
However, I fail to make it work with Docker and Docker Compose 🥀.

The idea would be to define the variables in a `.env` next to the `docker.compose.yml`, not next to the nextjs project. Then, pass the variables to the container at the startup.

I've prepared an example [here](https://github.com/YerayAlonso/next-runtime-env-with-docker-compose).
I get `undefined` at the client side.
Note the `__ENV.js` file is present, but empty (`window.__ENV = {}`).

**Comment by YerayAlonso** [comment]
Solved using a Dockerfile without multistage.

**Comment by tom-searle** [comment]
Just to add for anyone that stumbles across this that I was also able to solve this issue by using a Dockerfile without multistage 👍
