### ISSUE TITLE
How to set this up with a multi-stage docker built and using node server.js

### ISSUE THREAD

**Issue by abodnar** [expatfile/next-runtime-env#62]
When following the Docker build that Vercel recommends here (https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile), they use a multi stage build and runs `node server.js` when it starts.

Because of this, next-runtime-env does not execute and doesn't generate the `__ENV.js` file that is needed.

Not sure if there's some way make this work like https://github.com/kHRISl33t/runtime-env-cra did for the create-react-app projects.

**Comment by finlaysawyer** [comment]
I ended up adding the following line to my Docker entrypoint:

`node -e "const { configureRuntimeEnv } = require('next-runtime-env/build/configure'); configureRuntimeEnv();"`

That ensures that environment variables are loaded before `node server.js` starts.

**Comment by nathanmrtns** [comment]
@bhl-0 I just found the same problem in my setup

**Comment by HofmannZ** [comment]
If you're using the App Router, you no longer need to update your `next.config.js` to use this package. That would indirectly resolve your issue 🙂

We've completely revamped our solution to support Server Components and the App Router. 🙌

Please check the [development](https://github.com/expatfile/next-runtime-env/tree/development) branch for docs and examples.

We've also published a version [2.0.0-alpha.1 on NPM](https://www.npmjs.com/package/next-runtime-env/v/2.0.0-alpha.1). 🚀
