### ISSUE TITLE
✨ Next.js 13 - App Router Support

### ISSUE THREAD

**Issue by HofmannZ** [expatfile/next-runtime-env#69]
This issue is an overarching ticket to track the App Router support.

- [x] Support client components reading environment variables at runtime.
- [x] Support server components reading environment variables at runtime. (See: #35)
- [x] Fix client-side hydration.

**Comment by HofmannZ** [comment]
This is now supported in [v2.0.0-alpha.1](https://github.com/expatfile/next-runtime-env/releases/tag/v2.0.0-alpha.1) 🚀

**Comment by lucgagan** [comment]
Are the setup instructions the same?

i.e. Do we still need to include `<script src="/__ENV.js" />`?

**Comment by lucgagan** [comment]
@HofmannZ Do you have a minimal example of how to set this up with app/ router?

**Comment by HofmannZ** [comment]
@lucgagan - Yes! Check out the [development](https://github.com/expatfile/next-runtime-env/tree/development) branch, it has docs and examples.

We've also published version [2.0.0-alpha.3 on NPM](https://www.npmjs.com/package/next-runtime-env/v/2.0.0-alpha.3). 🚀

**Comment by lucgagan** [comment]
Worked flawlessly 👨‍🍳
