### ISSUE TITLE
Supporting output: 'standalone' Configuration

### ISSUE THREAD

**Issue by kalebdf** [expatfile/next-runtime-env#72]
Excited to find this package supporting the Build Once, Run Anywhere philosophy.

In order to keep our docker container super tiny, we turned on `standalone` output within the `next.config.js`.
```
const nextConfig = {
  // Automatically leverage output traces to reduce image size
  // https://nextjs.org/docs/advanced-features/output-file-tracing
  output: 'standalone',
}
```

We run `npm run build` and the `public/__ENV.js` is generated. However, that's at build time. We then copy over the `public` folder into `.next/standalone/public` as well as `.next/static` into `.next/standalone/.next/static`. 

From the [docs](https://nextjs.org/docs/advanced-features/output-file-tracing):
> This minimal server does not copy the `public` or `.next/static` folders by default as these should ideally be handled by a CDN instead, although these folders can be copied to the `standalone/public` and `standalone/.next/static` folders manually, after which `server.js` file will serve these automatically.

When we start up our built application, `NEXT_PUBLIC_FOO=foo node .next/standalone/server.js`, the plugin's code to write the public environment variables does not seem to run. The `public/__ENV.js` is not created and/or the plugin code never executes.

Have you experienced this before with the `output: 'standalone'`?

Any help would be appreciated! Thank you.

**Comment by ChristopherCapito** [comment]
I am facing a somewhat similar issue. I am using next experimental compile and the standalone output. I do have an __ENV.js but it is empty. Building it locally seems to work fine, though given that might be because I have a local .env file.

Interestingly, everything works just fine as far as Server Components go.

**Comment by HofmannZ** [comment]
Hi!

Unfortunately, we've not tested this package with standalone mode. We currently don't have it on our road map either. But we're happy to support anyone that is willing to explore a solution. :)

**Comment by HofmannZ** [comment]
@kalebdf @ChristopherCapito - There's an update where we've moved away from utilizing the `public/__ENV.js` file. Although I haven't verified its compatibility with `standalone` builds yet, I'm optimistic that it could work and wanted to make sure you were both aware of this change 🙂

**Comment by kalebdf** [comment]
We are currently successfully running `next-runtime-env@2.0.0-alpha.3` with Next 14 and `output: 'standalone'` config with Docker. Everything works well! Thanks, @HofmannZ 👏 👍 

We had to tweak/hack a few things back with v1 to make standalone work. However, we eagerly migrated to v2 in mid-October, removed all our hacks, and v2 been working well for us. We do miss the ease of the `env()` accessor, but understand. We'll be upgrading to v3 here soon.

**Comment by HofmannZ** [comment]
@kalebdf - Glad to hear everything woks now 🙂.

May I suggest holding back migrating to v3, as we're working on v4 already which brings back some ease of use features from v1 like the `env()` utility.

In v4 we're introducing a new way to create `window.__ENV`, specifically using a script React Server Components. This wil also allow you to use the environment variables outside a react component (like in v1.)

You can checkout an early preview here: https://github.com/expatfile/next-runtime-env/pull/92 (we basically still have to write some docs, that's it 😉)

We expect to ship v4 somewhere next week.

**Comment by kalebdf** [comment]
@chr1s1k Sure thing. We got `v1.7.0-alpha.1` to run by adding the following two commands in the Dockerfile in the `runner` stage after the `npm run build` step in the `builder` stage:
```
##
# Production image, copy all the files and run next
##
FROM base AS runner

# ...

COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# ...

# Need the next-runtime-env bc the package needs to be there at runtime & standalone doesn't package it up.
RUN npm install next-runtime-env@1.7.0-alpha.1 --omit=optional --prefer-offline --no-audit
RUN sed -i 's/const nextConfig =/const { configureRuntimeEnv } = require("next-runtime-env\/build\/configure");configureRuntimeEnv({subdirectory:"nextassets\/"});const nextConfig =/' server.js

# ...
```

Like I mentioned last year, we moved up to v2 are currently using `v2.0.1`.

**Comment by thenonameguy** [comment]
> @chr1s1k Sure thing. We got `v1.7.0-alpha.1` to run by adding the following two commands (install the package + sed command) in the Dockerfile in the `runner` stage after the `npm run build` step in the `builder` stage:
> 
> ```
> ##
> # Production image, copy all the files and run next
> ##
> FROM base AS runner
> 
> # ...
> 
> COPY --from=builder --chown=nextjs:nodejs /app/public ./public
> COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
> COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
> 
> # ...
> 
> # Need the next-runtime-env bc the package needs to be there at runtime & standalone doesn't package it up.
> RUN npm install next-runtime-env@1.7.0-alpha.1 --omit=optional --prefer-offline --no-audit
> RUN sed -i 's/const nextConfig =/const { configureRuntimeEnv } = require("next-runtime-env\/build\/configure");configureRuntimeEnv({subdirectory:"nextassets\/"});const nextConfig =/' server.js
> 
> # ...
> ```
> 
> Like I mentioned last year, we upgraded to v2 and are currently using `v2.0.1`.

Thanks, it works great! The yarn equivalent is:

```
RUN yarn add next-runtime-env@1.7.4 --no-optional --prefer-offline --no-audit
```

**Comment by khsily** [comment]
Here's what i did.

- Next 14 (Page Router)
- next-runtime-env 1.7.3

First, create `server.prod.js`

```js
const path = require('path');

const { configureRuntimeEnv } = require('next-runtime-env/build/configure');
configureRuntimeEnv();

require(path.join(__dirname, 'server.js'));
const env = process.env.NEXT_PUBLIC_ENV;
console.log(`Server Environment: ${env}`);
```

Then, copy it to standalone folder on build time.
```bash
$ cp server.prod.js .next/standalone/

# You also need to copy needed pacakges to run next-runtime-env
$ cp -r node_modules/next-runtime-env .next/standalone/node_modules/
$ cp -r node_modules/chalk .next/standalone/node_modules/
```

Now, run `server.prod.js` instead of `server.js`
```bash
$ node ./.next/standalone/server.prod.js
```

**Comment by dsteinbach-ep** [comment]
@khsily and if you want to load up vars from env files before generating config values you can do this:
```
const path = require('path');

const { loadEnvConfig } = require('@next/env');

const projectDir = process.cwd();

loadEnvConfig(projectDir)

const { configureRuntimeEnv } = require('next-runtime-env/build/configure');
configureRuntimeEnv();

require(path.join(__dirname, 'server.js'));
```
