### ISSUE TITLE
📣 Dropping support for Page Router in version 2.x

### ISSUE THREAD

**Issue by HofmannZ** [expatfile/next-runtime-env#79]
From version `2.x` onwards, we plan only to support the App Router as the solution is fundamentally different. (No longer uses the `_ENV.js` file in the public folder.)

We're supporting the Page Router on the `1.x` branch. We will keep pushing security updates and keep accepting pull requests for it. (Our company still has some front-ends depending on it 🙂)

**Comment by TaffarelJr** [comment]
Sounds awesome!
Is there an estimated timeframe on when 2.x might be available?

**Comment by carlos-dubon** [comment]
Does this new 2.0 version work algonside pages router? We have a big codebase, and plan to move to the app router progressively as it was intented to be.

**Comment by HofmannZ** [comment]
@carlos-dubon The version `1.x` branch will continue to get security updates (we have a couple frontends using it still.)

That said, we will not be pushing any new features to this branch.
