### ISSUE TITLE
Issue when working with route.ts

### ISSUE THREAD

**Issue by bagelbits** [expatfile/next-runtime-env#82]
## Package versions

* `next-runtime-env`: `2.0.0-alpha.3`
* `next` versions:
  * 13.5.5
  * 13.5.6
  * 14.0.0

## Issue

I am running into an issue using this package with routes:

```typescript
//app/api/v1/companies/route.ts
export async function GET(request: NextRequest) {
  return Response.json({ foo: process.env.NEXT_PUBLIC_BAR })
}

export const dynamic = 'force-dynamic'
```

This is still returning the build time environment variables instead of the runtime environment variables. Am I doing something wrong?

**Comment by bagelbits** [comment]
I'm going to make sure I'm on the latest Next.js first.

**Comment by bagelbits** [comment]
This is an issue on these versions of Next.js:
* 13.5.5
* 13.5.6
* 14.0.0

**Comment by HofmannZ** [comment]
I'm **not** able to reproduce your issue. To confirm I've added a route handler to the example.

You can try it out yourself:

1. Clone the repo
2. Checkout the `development` branch
3. `cd` to the example `with-app-router`
4. Run `pnpm build`
5. Run `NEXT_PUBLIC_FOO=foo-value BAR=bar-value BAZ=baz-value pnpm start`
6. Visit `http://localhost:3000/api/bar-baz` and see the values of the runtime env vars returned.

Can you check if your implementation differs from the example?

**Comment by bagelbits** [comment]
@HofmannZ I found where my implementation differs, but I don't know if this is working as intended.

## Steps to replicate

1. Add a `.env.local` file:

```.env
NEXT_PUBLIC_FOO="yes"
BAR="hello"
BAZ="world"
```

2. Change `examples/with-app-router/src/app/api/bar-baz` to:

```js
export async function GET() {
  return Response.json({
    bar: process.env.BAR,
    baz: process.env.BAZ,
    foo: process.env.NEXT_PUBLIC_FOO,
  });
}

export const dynamic = 'force-dynamic';
```

3. `pnpm build`
4. `NEXT_PUBLIC_FOO=foo-value BAR=bar-value BAZ=baz-value pnpm start`

### Expected

```json
{"bar":"bar-value","baz":"baz-value","foo":"foo-value"}
```

### Actual

```json
{"bar":"bar-value","baz":"baz-value","foo":"yes"}
```

**Comment by bagelbits** [comment]
@HofmannZ Amusingly, if you don't have the `.env.local` file. This works just fine. But it's inconsistent that `.env.local` overrides the `NEXT_PUBLIC_*` but not the normal ENV vars. Is that just the nature of how `NEXT_PUBLIC_*` works?

**Comment by HofmannZ** [comment]
This is due to how nextjs' build process works. They still set the public envs to a static string if they are declared in your `.env`.

There are two solutions:

1. Remove the `.env` file.
2. Remove the `NEXT_PUBLIC_` prefix.

> If you choose option 2, and you need to access the env var on both the server and the client, you can use the `makeEnvPublic` utility to automatically create the prefixed variable.

Let me know if that helps ✌️

**Comment by bagelbits** [comment]
@HofmannZ That 100% worked! Thank you so much for the clarification!
