### ISSUE TITLE
 question about injecting environment variable thorugh docker run --env

### ISSUE THREAD

**Issue by hyun11732** [expatfile/next-runtime-env#84]
Hi, I am really suffering from trying to inject environment varaible through docker run --env and i found your package.

In Next JS, I tried

const temp - () = > {
const { NEXT_PUBLIC_FOO  } = useEnvContext();
console.log(NEXT_PUBLIC_FOO );
};
export default temp;

and did docker run XXX --env NEXT_PUBLIC_FOO=hi

but console.log still prints undefined.... I dont think it recognizes my runtime environment variable injected from docker run --env.

Is there any solution?

Thank you!! please help me !!!

**Comment by HofmannZ** [comment]
@hyun11732 - Did you add the `PublicEnvProvider` to your layout? And this you add `export const dynamic = 'force-dynamic';` to that layout?

See: https://github.com/expatfile/next-runtime-env#getting-started-
